// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChVmnSen9IgRf3cB1RxZtaNuomfaO1KO0',
    appId: '1:156826465887:web:8bb87245087c1b98d04dea',
    messagingSenderId: '156826465887',
    projectId: 'evaluapp-a4055',
    authDomain: 'evaluapp-a4055.firebaseapp.com',
    databaseURL: 'https://evaluapp-a4055-default-rtdb.firebaseio.com',
    storageBucket: 'evaluapp-a4055.appspot.com',
    measurementId: 'G-1J7ZN0ZBM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKs8gZBc_eKlg46uPq92fdiD_eTZE2yC8',
    appId: '1:156826465887:android:d7f7151ea1fba3aad04dea',
    messagingSenderId: '156826465887',
    projectId: 'evaluapp-a4055',
    databaseURL: 'https://evaluapp-a4055-default-rtdb.firebaseio.com',
    storageBucket: 'evaluapp-a4055.appspot.com',
  );
}
